---
pool:
  name: Azure Pipelines
  vmImage: ubuntu-22.04

trigger:
  - main

steps:
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      golas: 'package' 
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      jdkVersionOption:  '1.17'
       